# Generated by Django 2.2.3 on 2019-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_system_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'system', 'verbose_name_plural': 'systems'},
        ),
    ]
