# Generated by Django 2.2.3 on 2019-07-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_auto_20190718_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity_levels', models.FloatField(blank=True, null=True)),
                ('temp_levels', models.FloatField(blank=True, null=True)),
                ('ph_levels', models.FloatField(blank=True, null=True)),
                ('oxygen_levels', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.System')),
            ],
        ),
    ]
