# Generated by Django 2.2.3 on 2019-07-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_condition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcondition',
            name='system',
        ),
    ]
