# Generated by Django 2.2.3 on 2019-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_condition', '0002_remove_systemcondition_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcondition',
            options={'verbose_name': 'systemcondition', 'verbose_name_plural': 'systemconditions'},
        ),
    ]
