# Generated by Django 2.2.3 on 2019-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_pump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempump',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systempump',
            name='pump_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systempump',
            name='pump_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='systempump',
            name='pump_photo',
            field=models.ImageField(blank=True, null=True, upload_to='system_crop_pump', verbose_name='system-pump-logo'),
        ),
        migrations.AddField(
            model_name='systempump',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='systempump',
            name='pump_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
