# Generated by Django 2.2.3 on 2019-07-18 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190718_1422'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_pump', '0002_auto_20190718_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='systempump',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systempump',
            name='system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.System'),
        ),
    ]
