# Generated by Django 2.2.3 on 2019-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_pump', '0003_auto_20190718_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systempump',
            options={'verbose_name': 'systempump', 'verbose_name_plural': 'systempumps'},
        ),
    ]
