# Generated by Django 2.2.3 on 2019-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropscanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropscanner',
            options={'verbose_name': 'cropscanner', 'verbose_name_plural': 'cropscanners'},
        ),
    ]
