# Generated by Django 2.2.3 on 2019-07-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_crop', '0002_auto_20190718_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemcrop',
            options={'verbose_name': 'systemcrop', 'verbose_name_plural': 'systemcrops'},
        ),
    ]
